### ISSUE TITLE
'Use Opportunity Dataset' button on home page produces error message in visualizer

### ISSUE THREAD

**Issue by samuel-thompsonn** [jpiland16/hmv_test#5]
On the HMV website, clicking the 'use opportunity dataset' button, selecting S1-Drill and pressing 'OK' leads to a loading screen, followed by the message "An error occured while loading the data file: The file could not be retrieved from the server. Try refreshing or resubmitting." with a red exclamation mark. Selecting S1-Drill using the side menu panel seems to work fine.

**Comment by jpiland16** [comment]
I think I was able to fix this with the [shared-visualizer-object](https://github.com/jpiland16/hmv_test/tree/shared-visualizer-object) branch. Specifically [this commit](https://github.com/jpiland16/hmv_test/commit/3fd37df6739124e24566263a82389f04227e4993) which should fix things having to do with using the URL to link to a file.
